#!/usr/bin/perl -w
use strict;

# I removed a bit of obfuscation code here to avoid outing DOW
# members.

# The following is a kludge to allow a symbolic link from the dow
# subdirectory to work. The idea is if the script is called from
# the dow subdir (using DOW .htaccess), then we can get the donor
# information. But dow.pm is located in a different place if this
# script is called from the top level or from within DOW.

BEGIN { 
    if (exists($ENV{REMOTE_USER})) {
	require dow;
	import dow;
    } else {
	require dow::dow;
	import dow::dow;
    }
}

my($DOW);

OpenDB();

$DOW = 0;
if (exists($ENV{REMOTE_USER})) {
    $DOW = 1;
}

purges();

PrintPageData();
CloseDB();

sub purges {
    if ($DOW) {
	DOW_header();
    } else {
	nonDOW_header();
    }
    showpurges();
    add("<p><hr><p><h2>History of the Purges List</h2>");
    add("<p>The purges list was originally instituted at the request of Abstrakt Workshop, the Wise Prophet at the time. DOW scripts generated the list of systems purged each turn from all members' data. The list of suspects was generated by hand by the DOW admin.\n");
    add("<p>At the time, I never anticipated that anybody would object to their data being used to track terminal purgers. As a result, there was never a poll on the issue, and members could not control whether their data were used or not. In fact, I never even <em>informed</em> members that their data were so used.\n");
    add("<p>Around turn 1285, a large number of terminals started to be purged. Since the scripts were not automated at that time, I got behind listing them. When I did update them, I almost immediately got an anonymous email pointing out that the page violated a basic DOW tenant -- that DOW data should not be shared with non-members. I must admit that this is quite correct.\n");
    add("<p>To remedy this problem, I changed the DOW scripts to allow each members to decide if his data should be used to track terminal purges. The new infrastructure requires rerunning the turn update code for each turn. Since this is quite a pain, I posted to the DOW forum, asking anybody who wanted to share their data for turns before this turn (1297) to contact me. Nobody did.\n");
    add("<p>Therefore, this page only tracks purges from turn 1297 onward. Since the previous page improperly leaked DOW data without members' permission, it will no longer be available.\n");
    add(StandardHTMLFooter());
}

sub showpurges {
    my($sth, $row);

    $sth = mydo("select * from purgedsystems where purgers=true order by turn desc, system;");

    add("<p><hr><p><table border><tr><th>Turn</th><th>System</th><th>Suspects (ships in-system when the purge occurred)</th></tr>\n");
    while ($row = $sth->fetchrow_hashref()) {
	add("<tr><td>", ($row->{turn}-1), "</td><td>$row->{system}</td><td>");
	add(join(', ', SelectAll("select ship from purgesuspects where purgeid=? and purgers=true;", $row->{purgeid})));
	add("</td></tr>\n");
    }
    add("</table>\n");
}

sub DOW_header {
    add(StandardHTMLHeader("Terminal Purge Information", "http://janin.org/dow/", ""));
    add("<h1>Terminal Purge Information</h1>\n");
    add("<p>This page attempts to track terminal purges so that the appropriate repurge can take place.\n");
    add("<p>Currently, you are");
    if (!SelectOne("select purgers from donors where ship=?;", $ENV{REMOTE_USER})) {
	add(" not");
    }
    add(" donating your information for purges. To change your settings, go to the <a href=\"ms.cgi\">Membership Data</a> page.\n");
}

sub nonDOW_header {
    add(StandardHTMLHeader("Terminal Purge Information", "http://janin.org/ninja/", ""));
    add("<h1>Terminal Purge Information</h1>\n");
    add("<p>This page attempts to track terminal purges so that the appropriate repurge can take place.\n");
    add("<p>This page is generated automatically using data contributed by members of <a href=\"dow.html\">DOW</a>.\n");
}
