INSERT INTO colonies (id, system, race, resource) VALUES (279, 'Pherda', 'Zebra', 'Hankies');
INSERT INTO colonies (id, system, race, resource) VALUES (185, 'Polaris', 'Otter', 'Jumpers');
INSERT INTO colonies (id, system, race, resource) VALUES (267, 'Polaris', 'Vole', 'New Tricks');
INSERT INTO colonies (id, system, race, resource) VALUES (211, 'Pollux', 'Pixie', 'Windows (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (277, 'Pollux', 'Zebra', 'Chocolate');
INSERT INTO colonies (id, system, race, resource) VALUES (295, 'Pollux', 'Squirrel', 'Xylophones');
INSERT INTO colonies (id, system, race, resource) VALUES (297, 'Pollux', 'Squirrel', 'Eye Robots');
INSERT INTO colonies (id, system, race, resource) VALUES (160, 'Procyon', 'Lizard', 'Snowmen');
INSERT INTO colonies (id, system, race, resource) VALUES (230, 'Procyon', 'Spider', 'Web Pages');
INSERT INTO colonies (id, system, race, resource) VALUES (110, 'Rastaban', 'Cat', 'Dilithium');
INSERT INTO colonies (id, system, race, resource) VALUES (112, 'Rastaban', 'Cat', 'Ray-guns (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (191, 'Rastaban', 'Penguin', 'Winegums');
INSERT INTO colonies (id, system, race, resource) VALUES (202, 'Rastaban', 'Pig', 'Emperors'' New Clothes');
INSERT INTO colonies (id, system, race, resource) VALUES (259, 'Rastaban', 'Turtle', 'Lists');
INSERT INTO colonies (id, system, race, resource) VALUES (266, 'Rastaban', 'Vole', 'Emperors'' New Clothes');
INSERT INTO colonies (id, system, race, resource) VALUES (91, 'Regulus', 'Ant', 'Mittens');
INSERT INTO colonies (id, system, race, resource) VALUES (142, 'Regulus', 'Groundhog', 'Dilithium');
INSERT INTO colonies (id, system, race, resource) VALUES (151, 'Regulus', 'Kangaroo', 'Hankies');
INSERT INTO colonies (id, system, race, resource) VALUES (180, 'Regulus', 'Otter', 'Scrap');
INSERT INTO colonies (id, system, race, resource) VALUES (263, 'Regulus', 'Vole', 'Xylophones');
INSERT INTO colonies (id, system, race, resource) VALUES (336, 'Regulus', 'Weasel', 'Ray-guns (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (186, 'Rigel', 'Otter', 'Marzipan');
INSERT INTO colonies (id, system, race, resource) VALUES (318, 'Rigel', 'Rat', 'Tea');
INSERT INTO colonies (id, system, race, resource) VALUES (92, 'Ross', 'Beetle', 'Puddings');
INSERT INTO colonies (id, system, race, resource) VALUES (107, 'Ross', 'Bird', 'New Tricks');
INSERT INTO colonies (id, system, race, resource) VALUES (84, 'Sadir', 'Ant', 'Scrap');
INSERT INTO colonies (id, system, race, resource) VALUES (114, 'Sadir', 'Cat', 'Euphoria (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (150, 'Sadir', 'Kangaroo', 'Fudge');
INSERT INTO colonies (id, system, race, resource) VALUES (212, 'Sadir', 'Rabbit', 'Scrap');
INSERT INTO colonies (id, system, race, resource) VALUES (224, 'Sadir', 'Sloth', 'Snowmen');
INSERT INTO colonies (id, system, race, resource) VALUES (319, 'Sadir', 'Rat', 'Winegums');
INSERT INTO colonies (id, system, race, resource) VALUES (333, 'Sadir', 'Weasel', 'Quad Trees');
INSERT INTO colonies (id, system, race, resource) VALUES (96, 'Schedar', 'Beetle', 'Snowmen');
INSERT INTO colonies (id, system, race, resource) VALUES (288, 'Schedar', 'Hamster', 'Snowmen');
INSERT INTO colonies (id, system, race, resource) VALUES (291, 'Schedar', 'Hamster', 'Lists');
INSERT INTO colonies (id, system, race, resource) VALUES (93, 'Scorpii', 'Beetle', 'Ninja Beer');
INSERT INTO colonies (id, system, race, resource) VALUES (128, 'Scorpii', 'Elf', 'Snowmen');
INSERT INTO colonies (id, system, race, resource) VALUES (144, 'Scorpii', 'Groundhog', 'Ray-guns (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (280, 'Scorpii', 'Zebra', 'Hats');
INSERT INTO colonies (id, system, race, resource) VALUES (296, 'Scorpii', 'Squirrel', 'Boardgames');
INSERT INTO colonies (id, system, race, resource) VALUES (89, 'Sirius', 'Ant', 'Jumpers');
INSERT INTO colonies (id, system, race, resource) VALUES (99, 'Sirius', 'Beetle', 'Lists');
INSERT INTO colonies (id, system, race, resource) VALUES (181, 'Sirius', 'Otter', 'Chocolate');
INSERT INTO colonies (id, system, race, resource) VALUES (303, 'Sirius', 'Worm', 'Steely Knives (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (271, 'Spica', 'Wasp', 'Steely Knives (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (275, 'Spica', 'Wasp', 'Windows (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (137, 'Tauri', 'Fish', 'Eye Robots');
INSERT INTO colonies (id, system, race, resource) VALUES (210, 'Tauri', 'Pixie', 'Euphoria (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (216, 'Tauri', 'Rabbit', 'Hats');
INSERT INTO colonies (id, system, race, resource) VALUES (255, 'Tauri', 'Turtle', 'Winegums');
INSERT INTO colonies (id, system, race, resource) VALUES (261, 'Tauri', 'Vole', 'Surprises');
INSERT INTO colonies (id, system, race, resource) VALUES (94, 'Thuban', 'Beetle', 'Tea');
INSERT INTO colonies (id, system, race, resource) VALUES (233, 'Thuban', 'Spider', 'Eye Robots');
INSERT INTO colonies (id, system, race, resource) VALUES (194, 'Vega', 'Penguin', 'Elvis Memorabilia');
INSERT INTO colonies (id, system, race, resource) VALUES (204, 'Vega', 'Pixie', 'Old Songs');
INSERT INTO colonies (id, system, race, resource) VALUES (240, 'Vega', 'Tiger', 'Ray-guns (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (88, 'Wezen', 'Ant', 'Hats');
INSERT INTO colonies (id, system, race, resource) VALUES (104, 'Wezen', 'Bird', 'Boardgames');
INSERT INTO colonies (id, system, race, resource) VALUES (171, 'Wezen', 'Lobster', 'New Tricks');
INSERT INTO colonies (id, system, race, resource) VALUES (244, 'Wolf', 'Troll', 'Scrap');
INSERT INTO colonies (id, system, race, resource) VALUES (246, 'Wolf', 'Troll', 'Fudge');
INSERT INTO colonies (id, system, race, resource) VALUES (329, 'Wolf', 'Snake', 'Eye Robots');
INSERT INTO colonies (id, system, race, resource) VALUES (338, 'Wolf', 'Weasel', 'Euphoria (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (174, 'Zosca', 'Monkey', 'Dilithium');
INSERT INTO colonies (id, system, race, resource) VALUES (177, 'Zosca', 'Monkey', 'Sharp Sticks (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (192, 'Zosca', 'Penguin', 'Snowmen');
INSERT INTO colonies (id, system, race, resource) VALUES (198, 'Zosca', 'Pig', 'Web Pages');
INSERT INTO colonies (id, system, race, resource) VALUES (235, 'Zosca', 'Spider', 'New Tricks');
INSERT INTO colonies (id, system, race, resource) VALUES (238, 'Zosca', 'Tiger', 'Dilithium');
INSERT INTO colonies (id, system, race, resource) VALUES (298, 'Castor', 'Squirrel', 'Emperors'' New Clothes');
INSERT INTO colonies (id, system, race, resource) VALUES (165, 'Centauri', 'Lobster', 'Surprises');
INSERT INTO colonies (id, system, race, resource) VALUES (167, 'Centauri', 'Lobster', 'Xylophones');
INSERT INTO colonies (id, system, race, resource) VALUES (245, 'Centauri', 'Troll', 'Chocolate');
INSERT INTO colonies (id, system, race, resource) VALUES (281, 'Centauri', 'Zebra', 'Jumpers');
INSERT INTO colonies (id, system, race, resource) VALUES (111, 'Cephei', 'Cat', 'Steely Knives (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (140, 'Cephei', 'Groundhog', 'Old Songs');
INSERT INTO colonies (id, system, race, resource) VALUES (156, 'Cephei', 'Lizard', 'Puddings');
INSERT INTO colonies (id, system, race, resource) VALUES (178, 'Cephei', 'Monkey', 'Euphoria (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (227, 'Cephei', 'Sloth', 'Lists');
INSERT INTO colonies (id, system, race, resource) VALUES (262, 'Cephei', 'Vole', 'Web Pages');
INSERT INTO colonies (id, system, race, resource) VALUES (293, 'Cephei', 'Squirrel', 'Surprises');
INSERT INTO colonies (id, system, race, resource) VALUES (101, 'Ceti', 'Bird', 'Surprises');
INSERT INTO colonies (id, system, race, resource) VALUES (157, 'Ceti', 'Lizard', 'Ninja Beer');
INSERT INTO colonies (id, system, race, resource) VALUES (113, 'Cygni', 'Cat', 'Sharp Sticks (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (143, 'Cygni', 'Groundhog', 'Steely Knives (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (213, 'Cygni', 'Rabbit', 'Chocolate');
INSERT INTO colonies (id, system, race, resource) VALUES (119, 'Deneb', 'Dog', 'Hankies');
INSERT INTO colonies (id, system, race, resource) VALUES (193, 'Deneb', 'Penguin', 'Beards');
INSERT INTO colonies (id, system, race, resource) VALUES (206, 'Deneb', 'Pixie', 'Dilithium');
INSERT INTO colonies (id, system, race, resource) VALUES (222, 'Deneb', 'Sloth', 'Tea');
INSERT INTO colonies (id, system, race, resource) VALUES (307, 'Deneb', 'Worm', 'Windows (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (106, 'Diphda', 'Bird', 'Emperors'' New Clothes');
INSERT INTO colonies (id, system, race, resource) VALUES (145, 'Diphda', 'Groundhog', 'Sharp Sticks (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (147, 'Diphda', 'Groundhog', 'Windows (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (172, 'Diphda', 'Monkey', 'Old Songs');
INSERT INTO colonies (id, system, race, resource) VALUES (201, 'Diphda', 'Pig', 'Eye Robots');
INSERT INTO colonies (id, system, race, resource) VALUES (231, 'Diphda', 'Spider', 'Xylophones');
INSERT INTO colonies (id, system, race, resource) VALUES (339, 'Diphda', 'Weasel', 'Windows (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (179, 'Eridani', 'Monkey', 'Windows (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (236, 'Eridani', 'Tiger', 'Old Songs');
INSERT INTO colonies (id, system, race, resource) VALUES (197, 'Fomalhaut', 'Pig', 'Surprises');
INSERT INTO colonies (id, system, race, resource) VALUES (243, 'Fomalhaut', 'Tiger', 'Windows (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (254, 'Fomalhaut', 'Turtle', 'Tea');
INSERT INTO colonies (id, system, race, resource) VALUES (190, 'Hamal', 'Penguin', 'Tea');
INSERT INTO colonies (id, system, race, resource) VALUES (221, 'Hamal', 'Sloth', 'Ninja Beer');
INSERT INTO colonies (id, system, race, resource) VALUES (242, 'Hamal', 'Tiger', 'Euphoria (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (316, 'Hamal', 'Rat', 'Puddings');
INSERT INTO colonies (id, system, race, resource) VALUES (108, 'Hydrae', 'Cat', 'Old Songs');
INSERT INTO colonies (id, system, race, resource) VALUES (170, 'Hydrae', 'Lobster', 'Emperors'' New Clothes');
INSERT INTO colonies (id, system, race, resource) VALUES (302, 'Hydrae', 'Worm', 'Dilithium');
INSERT INTO colonies (id, system, race, resource) VALUES (312, 'Hydrae', 'Goblin', 'Hats');
INSERT INTO colonies (id, system, race, resource) VALUES (335, 'Hydrae', 'Weasel', 'Steely Knives (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (337, 'Hydrae', 'Weasel', 'Sharp Sticks (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (123, 'Indi', 'Dog', 'Mittens');
INSERT INTO colonies (id, system, race, resource) VALUES (139, 'Indi', 'Fish', 'New Tricks');
INSERT INTO colonies (id, system, race, resource) VALUES (153, 'Indi', 'Kangaroo', 'Jumpers');
INSERT INTO colonies (id, system, race, resource) VALUES (292, 'Indi', 'Squirrel', 'Videos');
INSERT INTO colonies (id, system, race, resource) VALUES (294, 'Indi', 'Squirrel', 'Web Pages');
INSERT INTO colonies (id, system, race, resource) VALUES (299, 'Indi', 'Squirrel', 'New Tricks');
INSERT INTO colonies (id, system, race, resource) VALUES (301, 'Indi', 'Worm', 'Quad Trees');
INSERT INTO colonies (id, system, race, resource) VALUES (134, 'Kapetyn', 'Fish', 'Web Pages');
INSERT INTO colonies (id, system, race, resource) VALUES (330, 'Kapetyn', 'Snake', 'Emperors'' New Clothes');
INSERT INTO colonies (id, system, race, resource) VALUES (162, 'Kochab', 'Lizard', 'Elvis Memorabilia');
INSERT INTO colonies (id, system, race, resource) VALUES (225, 'Kochab', 'Sloth', 'Beards');
INSERT INTO colonies (id, system, race, resource) VALUES (248, 'Kochab', 'Troll', 'Hats');
INSERT INTO colonies (id, system, race, resource) VALUES (253, 'Kochab', 'Turtle', 'Ninja Beer');
INSERT INTO colonies (id, system, race, resource) VALUES (146, 'Kruger', 'Groundhog', 'Euphoria (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (309, 'Kruger', 'Goblin', 'Chocolate');
INSERT INTO colonies (id, system, race, resource) VALUES (313, 'Kruger', 'Goblin', 'Jumpers');
INSERT INTO colonies (id, system, race, resource) VALUES (127, 'Lupi', 'Elf', 'Winegums');
INSERT INTO colonies (id, system, race, resource) VALUES (189, 'Lupi', 'Penguin', 'Ninja Beer');
INSERT INTO colonies (id, system, race, resource) VALUES (257, 'Lupi', 'Turtle', 'Beards');
INSERT INTO colonies (id, system, race, resource) VALUES (273, 'Lupi', 'Wasp', 'Sharp Sticks (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (310, 'Lupi', 'Goblin', 'Fudge');
INSERT INTO colonies (id, system, race, resource) VALUES (100, 'Lyrae', 'Bird', 'Videos');
INSERT INTO colonies (id, system, race, resource) VALUES (205, 'Lyrae', 'Pixie', 'Quad Trees');
INSERT INTO colonies (id, system, race, resource) VALUES (260, 'Lyrae', 'Vole', 'Videos');
INSERT INTO colonies (id, system, race, resource) VALUES (282, 'Lyrae', 'Zebra', 'Marzipan');
INSERT INTO colonies (id, system, race, resource) VALUES (305, 'Lyrae', 'Worm', 'Sharp Sticks (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (317, 'Lyrae', 'Rat', 'Ninja Beer');
INSERT INTO colonies (id, system, race, resource) VALUES (332, 'Lyrae', 'Weasel', 'Old Songs');
INSERT INTO colonies (id, system, race, resource) VALUES (116, 'Markab', 'Dog', 'Scrap');
INSERT INTO colonies (id, system, race, resource) VALUES (149, 'Markab', 'Kangaroo', 'Chocolate');
INSERT INTO colonies (id, system, race, resource) VALUES (215, 'Markab', 'Rabbit', 'Hankies');
INSERT INTO colonies (id, system, race, resource) VALUES (237, 'Markab', 'Tiger', 'Quad Trees');
INSERT INTO colonies (id, system, race, resource) VALUES (183, 'Merak', 'Otter', 'Hankies');
INSERT INTO colonies (id, system, race, resource) VALUES (283, 'Merak', 'Zebra', 'Mittens');
INSERT INTO colonies (id, system, race, resource) VALUES (306, 'Merak', 'Worm', 'Euphoria (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (122, 'Mira', 'Dog', 'Marzipan');
INSERT INTO colonies (id, system, race, resource) VALUES (274, 'Mirfak', 'Wasp', 'Euphoria (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (331, 'Mirfak', 'Snake', 'New Tricks');
INSERT INTO colonies (id, system, race, resource) VALUES (182, 'Mizar', 'Otter', 'Fudge');
INSERT INTO colonies (id, system, race, resource) VALUES (249, 'Mizar', 'Troll', 'Jumpers');
INSERT INTO colonies (id, system, race, resource) VALUES (322, 'Mizar', 'Rat', 'Elvis Memorabilia');
INSERT INTO colonies (id, system, race, resource) VALUES (87, 'Olympus', 'Ant', 'Hankies');
INSERT INTO colonies (id, system, race, resource) VALUES (95, 'Olympus', 'Beetle', 'Winegums');
INSERT INTO colonies (id, system, race, resource) VALUES (115, 'Olympus', 'Cat', 'Windows (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (148, 'Olympus', 'Kangaroo', 'Scrap');
INSERT INTO colonies (id, system, race, resource) VALUES (166, 'Olympus', 'Lobster', 'Web Pages');
INSERT INTO colonies (id, system, race, resource) VALUES (173, 'Olympus', 'Monkey', 'Quad Trees');
INSERT INTO colonies (id, system, race, resource) VALUES (199, 'Olympus', 'Pig', 'Xylophones');
INSERT INTO colonies (id, system, race, resource) VALUES (214, 'Olympus', 'Rabbit', 'Fudge');
INSERT INTO colonies (id, system, race, resource) VALUES (220, 'Olympus', 'Sloth', 'Puddings');
INSERT INTO colonies (id, system, race, resource) VALUES (229, 'Olympus', 'Spider', 'Surprises');
INSERT INTO colonies (id, system, race, resource) VALUES (241, 'Olympus', 'Tiger', 'Sharp Sticks (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (250, 'Olympus', 'Troll', 'Marzipan');
INSERT INTO colonies (id, system, race, resource) VALUES (265, 'Olympus', 'Vole', 'Eye Robots');
INSERT INTO colonies (id, system, race, resource) VALUES (268, 'Olympus', 'Wasp', 'Old Songs');
INSERT INTO colonies (id, system, race, resource) VALUES (289, 'Olympus', 'Hamster', 'Beards');
INSERT INTO colonies (id, system, race, resource) VALUES (304, 'Olympus', 'Worm', 'Ray-guns (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (323, 'Olympus', 'Rat', 'Lists');
INSERT INTO colonies (id, system, race, resource) VALUES (334, 'Olympus', 'Weasel', 'Dilithium');
INSERT INTO colonies (id, system, race, resource) VALUES (195, 'Ophiuchi', 'Penguin', 'Lists');
INSERT INTO colonies (id, system, race, resource) VALUES (217, 'Ophiuchi', 'Rabbit', 'Jumpers');
INSERT INTO colonies (id, system, race, resource) VALUES (228, 'Ophiuchi', 'Spider', 'Videos');
INSERT INTO colonies (id, system, race, resource) VALUES (176, 'Pherda', 'Monkey', 'Ray-guns (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (187, 'Pherda', 'Otter', 'Mittens');
INSERT INTO colonies (id, system, race, resource) VALUES (208, 'Pherda', 'Pixie', 'Ray-guns (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (270, 'Pherda', 'Wasp', 'Dilithium');
INSERT INTO colonies (id, system, race, resource) VALUES (232, 'Achernar', 'Spider', 'Boardgames');
INSERT INTO colonies (id, system, race, resource) VALUES (239, 'Achernar', 'Tiger', 'Steely Knives (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (321, 'Achernar', 'Rat', 'Beards');
INSERT INTO colonies (id, system, race, resource) VALUES (135, 'Adhara', 'Fish', 'Xylophones');
INSERT INTO colonies (id, system, race, resource) VALUES (247, 'Adhara', 'Troll', 'Hankies');
INSERT INTO colonies (id, system, race, resource) VALUES (258, 'Adhara', 'Turtle', 'Elvis Memorabilia');
INSERT INTO colonies (id, system, race, resource) VALUES (325, 'Adhara', 'Snake', 'Surprises');
INSERT INTO colonies (id, system, race, resource) VALUES (118, 'Alcor', 'Dog', 'Fudge');
INSERT INTO colonies (id, system, race, resource) VALUES (290, 'Alcor', 'Hamster', 'Elvis Memorabilia');
INSERT INTO colonies (id, system, race, resource) VALUES (326, 'Alcor', 'Snake', 'Web Pages');
INSERT INTO colonies (id, system, race, resource) VALUES (327, 'Alcor', 'Snake', 'Xylophones');
INSERT INTO colonies (id, system, race, resource) VALUES (125, 'Aldebaran', 'Elf', 'Ninja Beer');
INSERT INTO colonies (id, system, race, resource) VALUES (131, 'Aldebaran', 'Elf', 'Lists');
INSERT INTO colonies (id, system, race, resource) VALUES (136, 'Aldebaran', 'Fish', 'Boardgames');
INSERT INTO colonies (id, system, race, resource) VALUES (152, 'Aldebaran', 'Kangaroo', 'Hats');
INSERT INTO colonies (id, system, race, resource) VALUES (188, 'Aldebaran', 'Penguin', 'Puddings');
INSERT INTO colonies (id, system, race, resource) VALUES (219, 'Aldebaran', 'Rabbit', 'Mittens');
INSERT INTO colonies (id, system, race, resource) VALUES (328, 'Aldebaran', 'Snake', 'Boardgames');
INSERT INTO colonies (id, system, race, resource) VALUES (102, 'Algol', 'Bird', 'Web Pages');
INSERT INTO colonies (id, system, race, resource) VALUES (105, 'Algol', 'Bird', 'Eye Robots');
INSERT INTO colonies (id, system, race, resource) VALUES (218, 'Algol', 'Rabbit', 'Marzipan');
INSERT INTO colonies (id, system, race, resource) VALUES (121, 'Alioth', 'Dog', 'Jumpers');
INSERT INTO colonies (id, system, race, resource) VALUES (168, 'Alioth', 'Lobster', 'Boardgames');
INSERT INTO colonies (id, system, race, resource) VALUES (276, 'Alioth', 'Zebra', 'Scrap');
INSERT INTO colonies (id, system, race, resource) VALUES (320, 'Alioth', 'Rat', 'Snowmen');
INSERT INTO colonies (id, system, race, resource) VALUES (324, 'Alioth', 'Snake', 'Videos');
INSERT INTO colonies (id, system, race, resource) VALUES (278, 'Alnitak', 'Zebra', 'Fudge');
INSERT INTO colonies (id, system, race, resource) VALUES (169, 'Alphard', 'Lobster', 'Eye Robots');
INSERT INTO colonies (id, system, race, resource) VALUES (203, 'Alphard', 'Pig', 'New Tricks');
INSERT INTO colonies (id, system, race, resource) VALUES (209, 'Alphard', 'Pixie', 'Sharp Sticks (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (130, 'Altair', 'Elf', 'Elvis Memorabilia');
INSERT INTO colonies (id, system, race, resource) VALUES (164, 'Altair', 'Lobster', 'Videos');
INSERT INTO colonies (id, system, race, resource) VALUES (184, 'Altair', 'Otter', 'Hats');
INSERT INTO colonies (id, system, race, resource) VALUES (286, 'Altair', 'Hamster', 'Tea');
INSERT INTO colonies (id, system, race, resource) VALUES (97, 'Antares', 'Beetle', 'Beards');
INSERT INTO colonies (id, system, race, resource) VALUES (141, 'Antares', 'Groundhog', 'Quad Trees');
INSERT INTO colonies (id, system, race, resource) VALUES (161, 'Antares', 'Lizard', 'Beards');
INSERT INTO colonies (id, system, race, resource) VALUES (163, 'Antares', 'Lizard', 'Lists');
INSERT INTO colonies (id, system, race, resource) VALUES (200, 'Antares', 'Pig', 'Boardgames');
INSERT INTO colonies (id, system, race, resource) VALUES (223, 'Antares', 'Sloth', 'Winegums');
INSERT INTO colonies (id, system, race, resource) VALUES (269, 'Antares', 'Wasp', 'Quad Trees');
INSERT INTO colonies (id, system, race, resource) VALUES (284, 'Antares', 'Hamster', 'Puddings');
INSERT INTO colonies (id, system, race, resource) VALUES (314, 'Antares', 'Goblin', 'Marzipan');
INSERT INTO colonies (id, system, race, resource) VALUES (154, 'Arcturus', 'Kangaroo', 'Marzipan');
INSERT INTO colonies (id, system, race, resource) VALUES (264, 'Arcturus', 'Vole', 'Boardgames');
INSERT INTO colonies (id, system, race, resource) VALUES (85, 'Aurigae', 'Ant', 'Chocolate');
INSERT INTO colonies (id, system, race, resource) VALUES (129, 'Aurigae', 'Elf', 'Beards');
INSERT INTO colonies (id, system, race, resource) VALUES (132, 'Aurigae', 'Fish', 'Videos');
INSERT INTO colonies (id, system, race, resource) VALUES (155, 'Aurigae', 'Kangaroo', 'Mittens');
INSERT INTO colonies (id, system, race, resource) VALUES (285, 'Aurigae', 'Hamster', 'Ninja Beer');
INSERT INTO colonies (id, system, race, resource) VALUES (311, 'Aurigae', 'Goblin', 'Hankies');
INSERT INTO colonies (id, system, race, resource) VALUES (98, 'Betelgeuse', 'Beetle', 'Elvis Memorabilia');
INSERT INTO colonies (id, system, race, resource) VALUES (103, 'Betelgeuse', 'Bird', 'Xylophones');
INSERT INTO colonies (id, system, race, resource) VALUES (117, 'Betelgeuse', 'Dog', 'Chocolate');
INSERT INTO colonies (id, system, race, resource) VALUES (120, 'Bootis', 'Dog', 'Hats');
INSERT INTO colonies (id, system, race, resource) VALUES (256, 'Bootis', 'Turtle', 'Snowmen');
INSERT INTO colonies (id, system, race, resource) VALUES (159, 'Canis', 'Lizard', 'Winegums');
INSERT INTO colonies (id, system, race, resource) VALUES (272, 'Canis', 'Wasp', 'Ray-guns (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (287, 'Canis', 'Hamster', 'Winegums');
INSERT INTO colonies (id, system, race, resource) VALUES (126, 'Canopus', 'Elf', 'Tea');
INSERT INTO colonies (id, system, race, resource) VALUES (158, 'Canopus', 'Lizard', 'Tea');
INSERT INTO colonies (id, system, race, resource) VALUES (207, 'Canopus', 'Pixie', 'Steely Knives (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (300, 'Canopus', 'Worm', 'Old Songs');
INSERT INTO colonies (id, system, race, resource) VALUES (308, 'Canopus', 'Goblin', 'Scrap');
INSERT INTO colonies (id, system, race, resource) VALUES (133, 'Capella', 'Fish', 'Surprises');
INSERT INTO colonies (id, system, race, resource) VALUES (252, 'Capella', 'Turtle', 'Puddings');
INSERT INTO colonies (id, system, race, resource) VALUES (315, 'Capella', 'Goblin', 'Mittens');
INSERT INTO colonies (id, system, race, resource) VALUES (90, 'Caph', 'Ant', 'Marzipan');
INSERT INTO colonies (id, system, race, resource) VALUES (124, 'Caph', 'Elf', 'Puddings');
INSERT INTO colonies (id, system, race, resource) VALUES (138, 'Caph', 'Fish', 'Emperors'' New Clothes');
INSERT INTO colonies (id, system, race, resource) VALUES (196, 'Caph', 'Pig', 'Videos');
INSERT INTO colonies (id, system, race, resource) VALUES (109, 'Castor', 'Cat', 'Quad Trees');
INSERT INTO colonies (id, system, race, resource) VALUES (175, 'Castor', 'Monkey', 'Steely Knives (!)');
INSERT INTO colonies (id, system, race, resource) VALUES (226, 'Castor', 'Sloth', 'Elvis Memorabilia');
INSERT INTO colonies (id, system, race, resource) VALUES (234, 'Castor', 'Spider', 'Emperors'' New Clothes');
INSERT INTO colonies (id, system, race, resource) VALUES (251, 'Castor', 'Troll', 'Mittens');
INSERT INTO colonies (id, system, race, resource) VALUES (86, 'Cygni', 'Ant', 'Fudge');
