INSERT INTO corona (id, danger, system) VALUES (1, 12, 'Tauri');
INSERT INTO corona (id, danger, system) VALUES (2, 11, 'Sirius');
INSERT INTO corona (id, danger, system) VALUES (3, 81, 'Mira');
INSERT INTO corona (id, danger, system) VALUES (4, 60, 'Rastaban');
INSERT INTO corona (id, danger, system) VALUES (5, 59, 'Star #26');
INSERT INTO corona (id, danger, system) VALUES (6, 46, 'Hamal');
INSERT INTO corona (id, danger, system) VALUES (7, 94, 'Ceti');
INSERT INTO corona (id, danger, system) VALUES (8, 73, 'Star #8');
INSERT INTO corona (id, danger, system) VALUES (9, 53, 'Mirfak');
INSERT INTO corona (id, danger, system) VALUES (10, 5, 'Ross');
INSERT INTO corona (id, danger, system) VALUES (11, 17, 'Thuban');
INSERT INTO corona (id, danger, system) VALUES (12, 75, 'Star #28');
INSERT INTO corona (id, danger, system) VALUES (13, 71, 'Canopus');
INSERT INTO corona (id, danger, system) VALUES (14, 35, 'Spica');
INSERT INTO corona (id, danger, system) VALUES (15, 64, 'Bootis');
INSERT INTO corona (id, danger, system) VALUES (16, 75, 'Star #20');
INSERT INTO corona (id, danger, system) VALUES (17, 8, 'Vega');
INSERT INTO corona (id, danger, system) VALUES (18, 12, 'Alnitak');
INSERT INTO corona (id, danger, system) VALUES (19, 92, 'Capella');
INSERT INTO corona (id, danger, system) VALUES (20, 42, 'Star #36');
INSERT INTO corona (id, danger, system) VALUES (21, 71, 'Star #34');
INSERT INTO corona (id, danger, system) VALUES (22, 22, 'Star #60');
INSERT INTO corona (id, danger, system) VALUES (23, 53, 'Betelgeuse');
INSERT INTO corona (id, danger, system) VALUES (24, 85, 'Star #50');
INSERT INTO corona (id, danger, system) VALUES (25, 93, 'Star #15');
INSERT INTO corona (id, danger, system) VALUES (26, 69, 'Aldebaran');
INSERT INTO corona (id, danger, system) VALUES (27, 20, 'Regulus');
INSERT INTO corona (id, danger, system) VALUES (28, 17, 'Draconis');
INSERT INTO corona (id, danger, system) VALUES (29, 73, 'Star #53');
INSERT INTO corona (id, danger, system) VALUES (30, 72, 'Star #13');
INSERT INTO corona (id, danger, system) VALUES (31, 24, 'Star #57');
INSERT INTO corona (id, danger, system) VALUES (32, 56, 'Diphda');
INSERT INTO corona (id, danger, system) VALUES (33, 72, 'Merak');
INSERT INTO corona (id, danger, system) VALUES (34, 35, 'Indi');
INSERT INTO corona (id, danger, system) VALUES (35, 15, 'Hydrae');
INSERT INTO corona (id, danger, system) VALUES (36, 75, 'Antares');
INSERT INTO corona (id, danger, system) VALUES (37, 83, 'Lyrae');
INSERT INTO corona (id, danger, system) VALUES (38, 64, 'Cephei');
INSERT INTO corona (id, danger, system) VALUES (39, 65, 'Lalande');
INSERT INTO corona (id, danger, system) VALUES (40, 85, 'Centauri');
INSERT INTO corona (id, danger, system) VALUES (41, 88, 'Castor');
INSERT INTO corona (id, danger, system) VALUES (42, 80, 'Ophiuchi');
INSERT INTO corona (id, danger, system) VALUES (43, 59, 'Zosca');
INSERT INTO corona (id, danger, system) VALUES (44, 7, 'Star #3');
INSERT INTO corona (id, danger, system) VALUES (45, 59, 'Star #44');
INSERT INTO corona (id, danger, system) VALUES (46, 49, 'Sadir');
INSERT INTO corona (id, danger, system) VALUES (47, 46, 'Barnard');
INSERT INTO corona (id, danger, system) VALUES (48, 3, 'Pollux');
INSERT INTO corona (id, danger, system) VALUES (49, 26, 'Adhara');
INSERT INTO corona (id, danger, system) VALUES (50, 79, 'Star #51');
INSERT INTO corona (id, danger, system) VALUES (51, 82, 'Star #31');
INSERT INTO corona (id, danger, system) VALUES (52, 7, 'Eridani');
INSERT INTO corona (id, danger, system) VALUES (53, 94, 'Scorpii');
INSERT INTO corona (id, danger, system) VALUES (54, 63, 'Star #33');
INSERT INTO corona (id, danger, system) VALUES (55, 92, 'Star #35');
INSERT INTO corona (id, danger, system) VALUES (56, 76, 'Algol');
INSERT INTO corona (id, danger, system) VALUES (57, 83, 'Star #24');
INSERT INTO corona (id, danger, system) VALUES (58, 51, 'Wezen');
INSERT INTO corona (id, danger, system) VALUES (59, 64, 'Star #0');
INSERT INTO corona (id, danger, system) VALUES (60, 38, 'Lupi');
INSERT INTO corona (id, danger, system) VALUES (61, 79, 'Aurigae');
INSERT INTO corona (id, danger, system) VALUES (62, 48, 'Star #55');
INSERT INTO corona (id, danger, system) VALUES (63, 8, 'Star #9');
INSERT INTO corona (id, danger, system) VALUES (64, 40, 'Star #7');
INSERT INTO corona (id, danger, system) VALUES (65, 65, 'Star #29');
INSERT INTO corona (id, danger, system) VALUES (66, 76, 'Pherda');
INSERT INTO corona (id, danger, system) VALUES (67, 52, 'Star #52');
INSERT INTO corona (id, danger, system) VALUES (68, 69, 'Rigel');
INSERT INTO corona (id, danger, system) VALUES (69, 55, 'Caph');
INSERT INTO corona (id, danger, system) VALUES (70, 92, 'Wolf');
INSERT INTO corona (id, danger, system) VALUES (71, 93, 'Alioth');
INSERT INTO corona (id, danger, system) VALUES (72, 36, 'Kochab');
INSERT INTO corona (id, danger, system) VALUES (73, 16, 'Star #41');
INSERT INTO corona (id, danger, system) VALUES (74, 59, 'Arcturus');
INSERT INTO corona (id, danger, system) VALUES (75, 93, 'Kruger');
INSERT INTO corona (id, danger, system) VALUES (76, 55, 'Star #11');
INSERT INTO corona (id, danger, system) VALUES (77, 99, 'Cygni');
INSERT INTO corona (id, danger, system) VALUES (78, 71, 'Star #10');
INSERT INTO corona (id, danger, system) VALUES (79, 61, 'Star #61');
INSERT INTO corona (id, danger, system) VALUES (80, 39, 'Star #14');
INSERT INTO corona (id, danger, system) VALUES (81, 92, 'Star #17');
INSERT INTO corona (id, danger, system) VALUES (82, 93, 'Alphard');
INSERT INTO corona (id, danger, system) VALUES (83, 91, 'Star #38');
INSERT INTO corona (id, danger, system) VALUES (84, 98, 'Star #37');
INSERT INTO corona (id, danger, system) VALUES (85, 0, 'Star #6');
INSERT INTO corona (id, danger, system) VALUES (86, 52, 'Star #19');
INSERT INTO corona (id, danger, system) VALUES (87, 45, 'Star #46');
INSERT INTO corona (id, danger, system) VALUES (88, 70, 'Star #42');
INSERT INTO corona (id, danger, system) VALUES (89, 59, 'Procyon');
INSERT INTO corona (id, danger, system) VALUES (90, 93, 'Star #12');
INSERT INTO corona (id, danger, system) VALUES (91, 98, 'Star #62');
INSERT INTO corona (id, danger, system) VALUES (92, 1, 'Star #32');
INSERT INTO corona (id, danger, system) VALUES (93, 88, 'Star #63');
INSERT INTO corona (id, danger, system) VALUES (94, 56, 'Star #30');
INSERT INTO corona (id, danger, system) VALUES (95, 13, 'Star #23');
INSERT INTO corona (id, danger, system) VALUES (96, 67, 'Star #54');
