INSERT INTO factories (resource, system, cost) VALUES ('Beards', 'Hamal', 100);
INSERT INTO factories (resource, system, cost) VALUES ('Boardgames', 'Indi', 200);
INSERT INTO factories (resource, system, cost) VALUES ('Chocolate', 'Merak', 50);
INSERT INTO factories (resource, system, cost) VALUES ('Dilithium', 'Lalande', 250);
INSERT INTO factories (resource, system, cost) VALUES ('Elvis Memorabilia', 'Centauri', 100);
INSERT INTO factories (resource, system, cost) VALUES ('Emperors'' New Clothes', 'Polaris', 200);
INSERT INTO factories (resource, system, cost) VALUES ('Euphoria (!)', 'Kapetyn', 500);
INSERT INTO factories (resource, system, cost) VALUES ('Eye Robots', 'Mirfak', 200);
INSERT INTO factories (resource, system, cost) VALUES ('Fudge', 'Hydrae', 50);
INSERT INTO factories (resource, system, cost) VALUES ('Hankies', 'Crucis', 50);
INSERT INTO factories (resource, system, cost) VALUES ('Hats', 'Kruger', 75);
INSERT INTO factories (resource, system, cost) VALUES ('Jumpers', 'Vega', 75);
INSERT INTO factories (resource, system, cost) VALUES ('Lists', 'Procyon', 125);
INSERT INTO factories (resource, system, cost) VALUES ('Marzipan', 'Canis', 75);
INSERT INTO factories (resource, system, cost) VALUES ('Mittens', 'Altair', 75);
INSERT INTO factories (resource, system, cost) VALUES ('New Tricks', 'Zosca', 250);
INSERT INTO factories (resource, system, cost) VALUES ('Ninja Beer', 'Aurigae', 100);
INSERT INTO factories (resource, system, cost) VALUES ('Old Songs', 'Regulus', 250);
INSERT INTO factories (resource, system, cost) VALUES ('Puddings', 'Draconis', 100);
INSERT INTO factories (resource, system, cost) VALUES ('Quad Trees', 'Ceti', 250);
INSERT INTO factories (resource, system, cost) VALUES ('Ray-guns (!)', 'Algol', 400);
INSERT INTO factories (resource, system, cost) VALUES ('Scrap', 'Adhara', 25);
INSERT INTO factories (resource, system, cost) VALUES ('Sharp Sticks (!)', 'Arcturus', 400);
INSERT INTO factories (resource, system, cost) VALUES ('Snowmen', 'Achernar', 100);
INSERT INTO factories (resource, system, cost) VALUES ('Steely Knives (!)', 'Thuban', 400);
INSERT INTO factories (resource, system, cost) VALUES ('Surprises', 'Cephei', 125);
INSERT INTO factories (resource, system, cost) VALUES ('Tea', 'Rastaban', 100);
INSERT INTO factories (resource, system, cost) VALUES ('Videos', 'Eridani', 125);
INSERT INTO factories (resource, system, cost) VALUES ('Web Pages', 'Barnard', 150);
INSERT INTO factories (resource, system, cost) VALUES ('Windows (!)', 'Tauri', 500);
INSERT INTO factories (resource, system, cost) VALUES ('Winegums', 'Cygni', 100);
INSERT INTO factories (resource, system, cost) VALUES ('Xylophones', 'Spica', 150);
