INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #63', 13, 20, 127);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Mira', 29, 14, 41);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Caph', 13, 32, 18);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Kochab', 6, 20, 34);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Indi', 19, 56, 32);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Hamal', 18, 28, 30);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #30', 0, 2, 94);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Alioth', 9, 3, 5);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #31', 21, 50, 95);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Mizar', 0, 14, 43);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #32', 10, 31, 96);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #33', 2, 32, 97);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Rigel', 12, 10, 51);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Alnitak', 24, 13, 6);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Ceti', 14, 35, 22);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #34', 27, 47, 98);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #35', 8, 49, 99);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #36', 2, 47, 100);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #37', 18, 57, 101);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Centauri', 24, 57, 20);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Alcor', 0, 32, 2);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #38', 14, 1, 102);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #39', 17, 29, 103);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Crucis', 25, 20, 23);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Sadir', 23, 53, 53);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Algol', 8, 7, 4);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Lupi', 3, 6, 37);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Tauri', 11, 15, 58);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Barnard', 19, 14, 12);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Cephei', 20, 33, 21);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Altair', 8, 34, 8);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Antares', 21, 39, 9);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Hydrae', 3, 16, 31);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Spica', 18, 15, 57);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Canis', 6, 59, 15);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Markab', 7, 21, 39);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Sirius', 12, 58, 56);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Aldebaran', 12, 46, 3);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Wolf', 11, 41, 62);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Aurigae', 23, 35, 11);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Pollux', 29, 27, 47);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Draconis', 9, 19, 27);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #40', 11, 26, 104);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #42', 4, 32, 106);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #43', 8, 24, 107);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Polaris', 19, 0, 46);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #44', 16, 49, 108);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #45', 18, 4, 109);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Arcturus', 10, 55, 10);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Thuban', 15, 8, 59);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #46', 13, 56, 110);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Wezen', 18, 39, 61);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #47', 17, 0, 111);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #48', 28, 35, 112);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Alphard', 4, 45, 7);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Canopus', 12, 20, 16);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #49', 10, 0, 113);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Procyon', 25, 35, 48);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Lalande', 20, 10, 36);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Eridani', 29, 56, 28);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Regulus', 5, 36, 50);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #10', 12, 31, 74);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #11', 5, 15, 75);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Capella', 9, 29, 17);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #12', 6, 47, 76);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Ophiuchi', 24, 38, 44);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Kruger', 16, 9, 35);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #13', 6, 31, 77);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #14', 14, 20, 78);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #15', 25, 7, 79);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #16', 22, 38, 80);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #17', 9, 49, 81);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #50', 27, 9, 114);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #18', 26, 6, 82);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #19', 5, 54, 83);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #51', 13, 44, 115);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #52', 4, 57, 116);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Ross', 28, 57, 52);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #53', 27, 31, 117);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #54', 21, 1, 118);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #55', 13, 8, 119);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #56', 17, 57, 120);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Zosca', 0, 55, 63);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #41', 2, 58, 105);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Rastaban', 19, 39, 49);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #57', 26, 45, 121);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #58', 1, 15, 122);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Castor', 21, 14, 19);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Vega', 28, 1, 60);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #59', 25, 49, 123);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Achernar', 26, 20, 0);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Olympus', 15, 35, -2);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Bootis', 10, 20, 14);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Merak', 20, 51, 40);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Schedar', 23, 10, 54);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Kapetyn', 2, 11, 33);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Fomalhaut', 11, 4, 29);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Scorpii', 22, 17, 55);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Deneb', 5, 4, 25);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Lyrae', 22, 49, 38);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Betelgeuse', 28, 19, 13);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Pherda', 15, 20, 45);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #0', 27, 20, 64);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #1', 16, 30, 65);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #20', 3, 55, 84);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #2', 17, 16, 66);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #3', 1, 4, 67);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Adhara', 3, 38, 1);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #21', 7, 41, 85);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Mirfak', 6, 8, 42);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #4', 26, 31, 68);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #22', 1, 49, 86);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #5', 21, 29, 69);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #6', 19, 58, 70);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #23', 22, 1, 87);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #7', 10, 44, 71);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #24', 28, 46, 88);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #25', 1, 26, 89);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #8', 19, 26, 72);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Diphda', 14, 47, 26);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #9', 7, 5, 73);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #26', 15, 36, 90);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #27', 15, 55, 91);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #60', 2, 1, 124);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #28', 14, 58, 92);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Cygni', 4, 8, 24);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #61', 23, 22, 125);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #29', 17, 46, 93);
INSERT INTO starcoords (system, x, y, destnum) VALUES ('Star #62', 24, 26, 126);
