INSERT INTO stargates (system1, system2, "key") VALUES ('Achernar', 'Procyon', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Adhara', 'Alioth', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Adhara', 'Ceti', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Alcor', 'Star #16', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Aldebaran', 'Capella', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Aldebaran', 'Star #55', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Algol', 'Spica', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Alioth', 'Adhara', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Alioth', 'Kruger', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Alnitak', 'Zosca', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Alphard', 'Fomalhaut', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Alphard', 'Sirius', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Altair', 'Castor', 3);
INSERT INTO stargates (system1, system2, "key") VALUES ('Altair', 'Merak', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Antares', 'Diphda', 3);
INSERT INTO stargates (system1, system2, "key") VALUES ('Antares', 'Thuban', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Arcturus', 'Betelgeuse', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Arcturus', 'Star #47', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Aurigae', 'Mizar', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Aurigae', 'Pollux', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Aurigae', 'Star #36', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Barnard', 'Star #14', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Betelgeuse', 'Arcturus', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Bootis', 'Crucis', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Bootis', 'Star #35', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Canis', 'Cygni', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Canopus', 'Mirfak', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Canopus', 'Spica', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Capella', 'Aldebaran', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Caph', 'Lupi', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Caph', 'Star #36', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Castor', 'Altair', 3);
INSERT INTO stargates (system1, system2, "key") VALUES ('Castor', 'Star #50', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Centauri', 'Vega', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Cephei', 'Star #24', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Ceti', 'Adhara', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Ceti', 'Markab', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Crucis', 'Bootis', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Cygni', 'Canis', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Cygni', 'Star #62', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Deneb', 'Rastaban', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Deneb', 'Star #12', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Diphda', 'Antares', 3);
INSERT INTO stargates (system1, system2, "key") VALUES ('Diphda', 'Lyrae', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Draconis', 'Kapetyn', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Draconis', 'Star #12', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Eridani', 'Star #4', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Fomalhaut', 'Alphard', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Hamal', 'Kochab', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Hamal', 'Sadir', 3);
INSERT INTO stargates (system1, system2, "key") VALUES ('Hydrae', 'Star #22', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Hydrae', 'Sirius', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Indi', 'Polaris', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Kapetyn', 'Draconis', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Kochab', 'Hamal', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Kruger', 'Alioth', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Kruger', 'Star #55', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Lalande', 'Star #5', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Lupi', 'Caph', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Lyrae', 'Diphda', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Lyrae', 'Thuban', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Markab', 'Ceti', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Markab', 'Scorpii', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Merak', 'Altair', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Merak', 'Zosca', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Mira', 'Thuban', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Mirfak', 'Canopus', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Mizar', 'Aurigae', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Mizar', 'Polaris', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Mizar', 'Ross', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Ophiuchi', 'Star #25', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Pherda', 'Thuban', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Polaris', 'Indi', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Polaris', 'Mizar', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Polaris', 'Spica', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Pollux', 'Aurigae', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Pollux', 'Regulus', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Procyon', 'Achernar', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Procyon', 'Star #63', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Rastaban', 'Deneb', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Regulus', 'Pollux', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Rigel', 'Star #27', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Ross', 'Mizar', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #1', 'Wolf', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #12', 'Deneb', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #12', 'Draconis', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #14', 'Barnard', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #16', 'Alcor', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #22', 'Hydrae', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #24', 'Cephei', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #25', 'Ophiuchi', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #27', 'Rigel', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #31', 'Tauri', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #35', 'Bootis', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #36', 'Aurigae', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #36', 'Caph', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #4', 'Eridani', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #40', 'Schedar', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #47', 'Arcturus', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #48', 'Wezen', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #5', 'Lalande', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #50', 'Castor', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #54', 'Vega', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #55', 'Aldebaran', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #55', 'Kruger', 4);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #62', 'Cygni', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Star #63', 'Procyon', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Sadir', 'Hamal', 3);
INSERT INTO stargates (system1, system2, "key") VALUES ('Sadir', 'Wezen', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Schedar', 'Star #40', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Scorpii', 'Markab', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Sirius', 'Alphard', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Sirius', 'Hydrae', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Spica', 'Algol', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Spica', 'Canopus', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Spica', 'Polaris', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Tauri', 'Star #31', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Thuban', 'Antares', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Thuban', 'Lyrae', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Thuban', 'Mira', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Thuban', 'Pherda', 6);
INSERT INTO stargates (system1, system2, "key") VALUES ('Vega', 'Centauri', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Vega', 'Star #54', 2);
INSERT INTO stargates (system1, system2, "key") VALUES ('Wezen', 'Star #48', 5);
INSERT INTO stargates (system1, system2, "key") VALUES ('Wezen', 'Sadir', 0);
INSERT INTO stargates (system1, system2, "key") VALUES ('Wolf', 'Star #1', 7);
INSERT INTO stargates (system1, system2, "key") VALUES ('Zosca', 'Alnitak', 1);
INSERT INTO stargates (system1, system2, "key") VALUES ('Zosca', 'Merak', 7);
