INSERT INTO statics (system, item) VALUES ('Wezen', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Wolf', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Zosca', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Zosca', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Zosca', 'Science School');
INSERT INTO statics (system, item) VALUES ('Zosca', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Centauri', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Centauri', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Centauri', 'Science School');
INSERT INTO statics (system, item) VALUES ('Centauri', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Ceti', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Crucis', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Crucis', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Crucis', 'Science School');
INSERT INTO statics (system, item) VALUES ('Crucis', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Cygni', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Deneb', 'Science School');
INSERT INTO statics (system, item) VALUES ('Diphda', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Draconis', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Draconis', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Draconis', 'Science School');
INSERT INTO statics (system, item) VALUES ('Draconis', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Eridani', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Eridani', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Fomalhaut', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Fomalhaut', 'Prison');
INSERT INTO statics (system, item) VALUES ('Fomalhaut', 'Science School');
INSERT INTO statics (system, item) VALUES ('Hamal', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Hamal', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Hamal', 'Science School');
INSERT INTO statics (system, item) VALUES ('Hamal', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Hydrae', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Hydrae', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Hydrae', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Hydrae', 'Science School');
INSERT INTO statics (system, item) VALUES ('Hydrae', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Indi', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Indi', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Indi', 'Science School');
INSERT INTO statics (system, item) VALUES ('Indi', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Kapetyn', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Kapetyn', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Kapetyn', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Kapetyn', 'Science School');
INSERT INTO statics (system, item) VALUES ('Kapetyn', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Kochab', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Kochab', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Kochab', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Kochab', 'Science School');
INSERT INTO statics (system, item) VALUES ('Kochab', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Kruger', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Kruger', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Lalande', 'Science School');
INSERT INTO statics (system, item) VALUES ('Lupi', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Lyrae', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Markab', 'Engineering Academy');
INSERT INTO statics (system, item) VALUES ('Markab', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Markab', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Markab', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Markab', 'Prison');
INSERT INTO statics (system, item) VALUES ('Markab', 'Science School');
INSERT INTO statics (system, item) VALUES ('Markab', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Merak', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Merak', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Merak', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Merak', 'Science School');
INSERT INTO statics (system, item) VALUES ('Merak', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Mirfak', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Mirfak', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Mirfak', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Mirfak', 'Science School');
INSERT INTO statics (system, item) VALUES ('Mirfak', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Mizar', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Mizar', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Olympus', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Olympus', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Ophiuchi', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Ophiuchi', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Pherda', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Pherda', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Pherda', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Pherda', 'Prison');
INSERT INTO statics (system, item) VALUES ('Pherda', 'Science School');
INSERT INTO statics (system, item) VALUES ('Pherda', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Polaris', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Polaris', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Polaris', 'Science School');
INSERT INTO statics (system, item) VALUES ('Polaris', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Procyon', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Regulus', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Regulus', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Regulus', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Regulus', 'Science School');
INSERT INTO statics (system, item) VALUES ('Regulus', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Rigel', 'Prison');
INSERT INTO statics (system, item) VALUES ('Ross', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Ross', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Ross', 'Science School');
INSERT INTO statics (system, item) VALUES ('Ross', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Star #10', 'Prison');
INSERT INTO statics (system, item) VALUES ('Star #13', 'Prison');
INSERT INTO statics (system, item) VALUES ('Star #14', 'Prison');
INSERT INTO statics (system, item) VALUES ('Star #22', 'Prison');
INSERT INTO statics (system, item) VALUES ('Star #39', 'Prison');
INSERT INTO statics (system, item) VALUES ('Star #41', 'Prison');
INSERT INTO statics (system, item) VALUES ('Star #49', 'Prison');
INSERT INTO statics (system, item) VALUES ('Star #55', 'Prison');
INSERT INTO statics (system, item) VALUES ('Sadir', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Sadir', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Sadir', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Sadir', 'Science School');
INSERT INTO statics (system, item) VALUES ('Sadir', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Schedar', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Schedar', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Schedar', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Schedar', 'Science School');
INSERT INTO statics (system, item) VALUES ('Schedar', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Scorpii', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Scorpii', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Sirius', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Sirius', 'Medical Academy');
INSERT INTO statics (system, item) VALUES ('Sirius', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Sirius', 'Science School');
INSERT INTO statics (system, item) VALUES ('Sirius', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Spica', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Tauri', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Tauri', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Tauri', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Tauri', 'Science School');
INSERT INTO statics (system, item) VALUES ('Tauri', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Thuban', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Thuban', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Thuban', 'Science School');
INSERT INTO statics (system, item) VALUES ('Thuban', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Vega', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Alioth', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Alphard', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Antares', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Arcturus', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Bootis', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Canopus', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Capella', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Caph', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Castor', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Centauri', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Cephei', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Diphda', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Fomalhaut', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Hamal', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Indi', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Kapetyn', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Lalande', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Lyrae', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Mirfak', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Olympus', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Regulus', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Ross', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Scorpii', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Sirius', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Vega', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Wezen', 'Ocean');
INSERT INTO statics (system, item) VALUES ('Achernar', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Alcor', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Alcor', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Alcor', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Alcor', 'Science Academy');
INSERT INTO statics (system, item) VALUES ('Alcor', 'Science School');
INSERT INTO statics (system, item) VALUES ('Alcor', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Aldebaran', 'Prison');
INSERT INTO statics (system, item) VALUES ('Algol', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Algol', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Algol', 'Science School');
INSERT INTO statics (system, item) VALUES ('Algol', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Alioth', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Alioth', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Alioth', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Alioth', 'Science School');
INSERT INTO statics (system, item) VALUES ('Alioth', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Alnitak', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Alnitak', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Alnitak', 'Prison');
INSERT INTO statics (system, item) VALUES ('Alnitak', 'Science School');
INSERT INTO statics (system, item) VALUES ('Alnitak', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Alphard', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Alphard', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Altair', 'Science School');
INSERT INTO statics (system, item) VALUES ('Antares', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Arcturus', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Aurigae', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Aurigae', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Aurigae', 'Prison');
INSERT INTO statics (system, item) VALUES ('Aurigae', 'Science School');
INSERT INTO statics (system, item) VALUES ('Aurigae', 'Weaponry Academy');
INSERT INTO statics (system, item) VALUES ('Aurigae', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Betelgeuse', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Betelgeuse', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Betelgeuse', 'Science School');
INSERT INTO statics (system, item) VALUES ('Betelgeuse', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Bootis', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Bootis', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Bootis', 'Prison');
INSERT INTO statics (system, item) VALUES ('Bootis', 'Science School');
INSERT INTO statics (system, item) VALUES ('Bootis', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Canis', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Canis', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Canis', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Canis', 'Science School');
INSERT INTO statics (system, item) VALUES ('Canis', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Canopus', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Capella', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Capella', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Capella', 'Science School');
INSERT INTO statics (system, item) VALUES ('Capella', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Caph', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Caph', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Caph', 'Science School');
INSERT INTO statics (system, item) VALUES ('Caph', 'Weaponry School');
INSERT INTO statics (system, item) VALUES ('Castor', 'Engineering School');
INSERT INTO statics (system, item) VALUES ('Castor', 'Hiring Hall');
INSERT INTO statics (system, item) VALUES ('Castor', 'Medical School');
INSERT INTO statics (system, item) VALUES ('Castor', 'Science School');
INSERT INTO statics (system, item) VALUES ('Castor', 'Weaponry School');
