INSERT INTO sysstarnet (system, terminal) VALUES ('Markab', 0);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #28', 1);
INSERT INTO sysstarnet (system, terminal) VALUES ('Rastaban', 2);
INSERT INTO sysstarnet (system, terminal) VALUES ('Canopus', 3);
INSERT INTO sysstarnet (system, terminal) VALUES ('Spica', 4);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #25', 5);
INSERT INTO sysstarnet (system, terminal) VALUES ('Bootis', 6);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #20', 7);
INSERT INTO sysstarnet (system, terminal) VALUES ('Sirius', 8);
INSERT INTO sysstarnet (system, terminal) VALUES ('Alcor', 9);
INSERT INTO sysstarnet (system, terminal) VALUES ('Vega', 10);
INSERT INTO sysstarnet (system, terminal) VALUES ('Ceti', 11);
INSERT INTO sysstarnet (system, terminal) VALUES ('Ross', 12);
INSERT INTO sysstarnet (system, terminal) VALUES ('Alnitak', 13);
INSERT INTO sysstarnet (system, terminal) VALUES ('Capella', 14);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #27', 15);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #8', 16);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #22', 17);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #36', 18);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #34', 19);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #1', 20);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #60', 21);
INSERT INTO sysstarnet (system, terminal) VALUES ('Betelgeuse', 22);
INSERT INTO sysstarnet (system, terminal) VALUES ('Mira', 23);
INSERT INTO sysstarnet (system, terminal) VALUES ('Hamal', 24);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #50', 25);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #15', 26);
INSERT INTO sysstarnet (system, terminal) VALUES ('Aldebaran', 27);
INSERT INTO sysstarnet (system, terminal) VALUES ('Tauri', 28);
INSERT INTO sysstarnet (system, terminal) VALUES ('Regulus', 29);
INSERT INTO sysstarnet (system, terminal) VALUES ('Draconis', 30);
INSERT INTO sysstarnet (system, terminal) VALUES ('Star #53', 31);
