INSERT INTO terrain (system, terrain) VALUES ('Star #30', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Mizar', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Alcor', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Zosca', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #3', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #58', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #25', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #22', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #60', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Kapetyn', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #33', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #36', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #41', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Lupi', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Hydrae', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Adhara', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Star #20', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Cygni', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #42', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Alphard', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #52', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Deneb', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Star #11', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Regulus', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #19', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Mirfak', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Kochab', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #13', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #12', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Canis', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #9', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Markab', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #21', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Algol', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #43', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Altair', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #35', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Alioth', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Draconis', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Capella', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #17', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #49', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Bootis', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Star #32', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #7', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Arcturus', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Fomalhaut', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Tauri', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #40', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Wolf', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Rigel', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Canopus', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #10', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Aldebaran', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Sirius', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #55', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #63', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Caph', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #51', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #46', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #38', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #14', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Ceti', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Diphda', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #28', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Thuban', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Pherda', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #26', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #27', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Kruger', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #1', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Olympus', 'Dyson Sphere');
INSERT INTO terrain (system, terrain) VALUES ('Star #44', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #47', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Star #2', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #39', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #29', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #56', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #45', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Spica', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Hamal', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Wezen', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #37', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Polaris', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Barnard', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #8', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Rastaban', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Indi', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Lalande', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Cephei', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Merak', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #6', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #54', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Castor', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #5', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Antares', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #31', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #23', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Scorpii', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #16', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Lyrae', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Schedar', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #61', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Aurigae', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Sadir', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Alnitak', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #62', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Ophiuchi', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Centauri', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #15', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Crucis', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Procyon', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #59', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #18', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Achernar', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #4', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Star #57', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #50', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #0', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #53', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #34', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Vega', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Betelgeuse', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Star #48', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Star #24', 'Asteroids');
INSERT INTO terrain (system, terrain) VALUES ('Ross', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Mira', 'Clear');
INSERT INTO terrain (system, terrain) VALUES ('Pollux', 'Nebula');
INSERT INTO terrain (system, terrain) VALUES ('Eridani', 'Nebula');
